CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT USAGE ON SCHEMA user_management TO usuario_db;
GRANT CREATE ON SCHEMA user_management TO usuario_db;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_management TO usuario_db;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA user_management TO usuario_db;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_management GRANT ALL PRIVILEGES ON TABLES TO usuario_db;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_management GRANT ALL PRIVILEGES ON SEQUENCES TO usuario_db;